<a href="https://colab.research.google.com/github/EvenSol/NeqSim-Colab/blob/master/notebooks/PVT/parameter_database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
%%capture
!pip install neqsim
!pip install wget

In [75]:
%%capture
!wget https://raw.githubusercontent.com/equinor/neqsim/master/src/main/resources/data/COMP.csv
!wget https://raw.githubusercontent.com/equinor/neqsim/master/src/main/resources/data/INTER.csv

In [76]:
import pandas as pd
comp_df = pd.read_csv('COMP.csv')
comp_df

,ID,NAME,CASnumber,COMPTYPE,COMPINDEX,FORMULA,MOLARMASS,LIQDENS,TC,PC,...,CPsolid5,CPliquid1,CPliquid2,CPliquid3,CPliquid4,CPliquid5,MCPR1,MCPR2,MCPR3,PARACHOR_CPA
0,1,methane,74-82-8,HC,1,CH4,16.043,0.422182,-82.590000,45.99,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.392340,0.00000,0.00000,77.300000
1,2,ethane,74-84-0,HC,2,C2H6,30.070,0.544459,32.170000,48.72,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.520050,0.00430,0.10292,108.900000
2,3,Cl-,0-0-0-0,ion,3,Cl-,35.450,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
3,4,Na+,0-0-0-0,ion,4,Na+,22.990,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
4,5,Mg++,0-0-0-0,ion,5,Mg++,24.310,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,1183,trans-12-DM-cy-C6,6876-23-9,HC,147,C,112.220,0.422182,322.777002,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
190,1184,cis-14-DM-cy-C6,624-29-3,HC,147,C,112.220,0.422182,325.000000,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
191,1185,trans-14-DM-cy-C6,2207-04-7,HC,147,C,112.220,0.422182,316.667017,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
192,1186,PG,57-55-6,glycol,1186,propyleneglycol,76.095,1.036000,352.850000,61.00,...,0.0,35540.0,436.78,-0.18486,0.0,0.0,0.910030,1.34996,-1.89002,151.817428
193,1187,ammonia,7664-41-7,other,1187,Nh3,17.031,0.730000,132.250000,113.00,...,0.0,105800.0,-362.23,0.93790,0.0,0.0,1.224003,-0.27350,-0.39823,87.543853

# Components

In [77]:
comp_df['NAME']

0                methane
1                 ethane
2                    Cl-
3                    Na+
4                   Mg++
             ...
189    trans-12-DM-cy-C6
190      cis-14-DM-cy-C6
191    trans-14-DM-cy-C6
192                   PG
193              ammonia
Name: NAME, Length: 194, dtype: object

# How to add a new component

In [78]:
component = { 'ID': len(comp_df), 'NAME': 'methane2', 'CASnumber': '74-82-8', 'COMPTYPE': 'HC', 'COMPINDEX': 1000, 'FORMULA':'CH4', 'MOLARMASS':16.04}
newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))
newcomp_df.to_csv('COMPupdated.csv')
newcomp_df

<ipython-input-78-306cf15eb095>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))

,ID,NAME,CASnumber,COMPTYPE,COMPINDEX,FORMULA,MOLARMASS,LIQDENS,TC,PC,...,CPsolid5,CPliquid1,CPliquid2,CPliquid3,CPliquid4,CPliquid5,MCPR1,MCPR2,MCPR3,PARACHOR_CPA
0,1,methane,74-82-8,HC,1,CH4,16.043,0.422182,-82.590000,45.99,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.392340,0.00000,0.00000,77.300000
1,2,ethane,74-84-0,HC,2,C2H6,30.070,0.544459,32.170000,48.72,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.520050,0.00430,0.10292,108.900000
2,3,Cl-,0-0-0-0,ion,3,Cl-,35.450,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
3,4,Na+,0-0-0-0,ion,4,Na+,22.990,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
4,5,Mg++,0-0-0-0,ion,5,Mg++,24.310,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,1184,cis-14-DM-cy-C6,624-29-3,HC,147,C,112.220,0.422182,325.000000,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
191,1185,trans-14-DM-cy-C6,2207-04-7,HC,147,C,112.220,0.422182,316.667017,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
192,1186,PG,57-55-6,glycol,1186,propyleneglycol,76.095,1.036000,352.850000,61.00,...,0.0,35540.0,436.78,-0.18486,0.0,0.0,0.910030,1.34996,-1.89002,151.817428
193,1187,ammonia,7664-41-7,other,1187,Nh3,17.031,0.730000,132.250000,113.00,...,0.0,105800.0,-362.23,0.93790,0.0,0.0,1.224003,-0.27350,-0.39823,87.543853
0,194,methane2,74-82-8,HC,1000,CH4,16.040,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# How to use new table in database 
How to set path to database (if not to use default database)

In [79]:
from neqsim import jNeqSim

jNeqSim.util.database.NeqSimDataBase.updateTable('COMP', '/content/COMPupdated.csv')


#and then use the new component and table

from neqsim.thermo import fluid

fluid1 = fluid('srk')
fluid1.addCOmponent('methane2', 1.0)
TPflash(fluid1)

AttributeError: ignored

# Interaction parameter database

In [ ]:
import pandas as pd
inter_df = pd.read_csv('INTER.csv')
inter_df

Adding a new interaction between methane2 and propane

In [ ]:
interNew = { 'ID': len(inter_df), 'COMP1': 'methane2', 'COMP2': 'propane', 'KIJSRK': 0.003}
newinter_df = inter_df.append(pd.DataFrame(interNew, index=[0])).fillna(0)
newinter_df.to_csv('INTERupdated.csv')
newinter_df

And then use the new interaction

In [ ]:
jNeqSim.util.database.NeqSimDataBase.updateTable('INTER', '/content/INTERupdated.csv')


#and then use the new component and table

from neqsim.thermo import fluid

fluid1 = fluid('srk')
fluid1.addCOmponent('methane2', 1.0)
fluid1.addCOmponent('propane', 1.0)
TPflash(fluid1)
#print(fluid1.getPhase(0).getMIxingRUle().getkij(0,1))

# Update parameters in the database

In [ ]:
comp_df.at[0,'TC']=-82.2590000 #updating critical temperature of methane
comp_df.to_csv('COMPupdatedparam.csv')
jNeqSim.util.database.NeqSimDataBase.updateTable('COMP', '/content/COMPupdatedparam.csv')

# Add new components using the Chemicals package
https://github.com/CalebBell/chemicals

https://chemicals.readthedocs.io/

In [92]:
pip install chemicals

SyntaxError: ignored

In [177]:
from chemicals.identifiers import CAS_from_any, search_chemical, pubchem_db
componentName = 'water' #enter compoent name/CAS number/etx
comp = search_chemical(componentName)
print(comp)
CAS_number = CAS_from_any(componentName)
FORMULA = comp.formula

<ChemicalMetadata, name=water, formula=H2O, smiles=O, MW=18.0153>

In [178]:
ID = comp_df.ID.max()+1
COMPINDEX = len(comp_df. index)+1

R = 8.3144598 # J/Kmol

from chemicals import CAS_from_any, MW, Tb, Tm, Tc, Pc, Vc, Hfus, Hfs, Hfl, Hfg, S0s, S0l, S0g, rho_to_API 
from chemicals.identifiers import ChemicalMetadata,pubchem_db 
from chemicals.iapws import iapws95_rhol_sat
from chemicals.acentric import omega
from chemicals.phase_change import Tb
from chemicals.reaction import Hfg

from chemicals.vapor_pressure import Psat_data_AntoinePoling
from chemicals.dipole import dipole_moment
from chemicals.volume import rho_data_COSTALD

MW = MW(CAS_number) # gr/mol

#https://chemicals.readthedocs.io/chemicals.critical.html#chemicals.critical.Tc_methods
TC = Tc(CAS_number)-273.15 #C
PC = Pc(CAS_number)/1e5 #bara
Vc = Vc(CAS_number)*1e6

#https://chemicals.readthedocs.io/chemicals.acentric.html
acsfact = omega(CAS_number)

#https://chemicals.readthedocs.io/chemicals.phase_change.html#boiling-point
NORMBOIL = Tb(CAS_number)-273.15 #C
PVMODEL = 'Classic'
Href = Hfg(CAS_number)

#https://chemicals.readthedocs.io/chemicals.volume.html#pure-low-pressure-liquid-correlations
from chemicals.volume import COSTALD,Vm_to_rho
normalliqdens = Vm_to_rho(COSTALD(NORMBOIL+273.15, TC+273.15,Vc/1e6,acsfact),MW)

# https://github.com/equinor/neqsim/blob/67bfec956176ffcad490a288fbcd7e17844f3a1c/src/main/java/neqsim/thermo/component/Component.java#L1277
# getCpA() + getCpB() * temperature + getCpC() * Math.pow(temperature, 2)+ getCpD() * Math.pow(temperature, 3) + getCpE() * Math.pow(temperature, 4); temperature in K
# https://chemicals.readthedocs.io/chemicals.heat_capacity.html#chemicals.heat_capacity.ShomateRange.calculate_integral
from chemicals.heat_capacity import Cp_data_Poling
try:
  cpdata = Cp_data_Poling.loc[CAS_number]
  CPA=cpdata['a0']*R
  CPB=cpdata['a1']*R
  CPC=cpdata['a2']*R
  CPD=cpdata['a3']*R
  CPE = cpdata['a4']*R 
except:
  CPA=37.978352
  CPB=-0.07461815
  CPC=0.0003018813
  CPD=0
  CPE = 0


#https://github.com/equinor/neqsim/blob/67bfec956176ffcad490a288fbcd7e17844f3a1c/src/main/java/neqsim/thermo/component/Component.java#L1194
#pow10 : Math.pow(10.0, AntoineA - (AntoineB / (temp + AntoineC - 273.15)));
#https://chemicals.readthedocs.io/chemicals.vapor_pressure.html#id62
try:
  AntoineVapPresLiqType = 'pow10KPa'
  antoinepol = Psat_data_AntoinePoling.loc[CAS_number]
  ANTOINEA = antoinepol['A']
  ANTOINEB = antoinepol['B']
  ANTOINEC = antoinepol['C']
  ANTOINED= 0.0
  ANTOINEE= 0.0
except:
  AntoineVapPresLiqType = 'pow10KPa'
  ANTOINEA =0
  ANTOINEB = 0
  ANTOINEC = 0
  ANTOINED= 0.0
  ANTOINEE= 0.0 
#https://chemicals.readthedocs.io/chemicals.dipole.html
#https://github.com/equinor/neqsim/blob/67bfec956176ffcad490a288fbcd7e17844f3a1c/src/main/java/neqsim/thermo/component/Component.java#L741
DIPOLEMOMENT = dipole_moment(CAS_number)

VISCFACT = 0.215

#https://chemicals.readthedocs.io/chemicals.volume.html?highlight=racket#chemicals.volume.Rackett
try:
  RACKETZ = rho_data_COSTALD.loc[CAS_number]['Z_RA']
  volcorrSRK_T = 0.0
except:
  RACKETZ = 0.0
  volcorrSRK_T = 0.0

#https://chemicals.readthedocs.io/chemicals.lennard_jones.html?highlight=molecular_diameter
from chemicals.lennard_jones import molecular_diameter
from chemicals.lennard_jones import Stockmayer
from chemicals.molecular_geometry import RG
try:
  LJDIAMETER = molecular_diameter(CAS_number)
  LJEPS = Stockmayer(CAS_number)
except:
  LJDIAMETER = 1.0
  LJEPS = 1.0

try:
  SphericalCoreRadius = RG(CAS_number)*1e10/2.0
except:
  SphericalCoreRadius = 1.0

#https://chemicals.readthedocs.io/chemicals.phase_change.html?highlight=Hfus#heat-of-fusion
HEATOFFUSION = Hfus(CAS_number)

#
from chemicals.triple import Tt, Pt
try:
  TRIPLEPOINTTEMPERATURE = Tt(CAS_number)
  TRIPLEPOINTPRESSURE = Pt(CAS_number)/1e5
  TRIPLEPOINTDENSITY = normalliqdens
except:
  TRIPLEPOINTTEMPERATURE = 0
  TRIPLEPOINTPRESSURE = 0
  TRIPLEPOINTDENSITY = 0

#https://chemicals.readthedocs.io/chemicals.phase_change.html?highlight=MELTING#module-chemicals.phase_change
from chemicals.phase_change import Tm
MELTINGPOINTTEMPERATURE= Tm(CAS_number)

from chemicals.reaction import Hfg
ENTHALPYOFFORMATION = Hfg(CAS_number)

In [174]:
component = {'ID': ID, 'NAME': componentName, 'CASnumber': CAS_number, 'COMPTYPE': componentName, 'COMPINDEX': COMPINDEX, 'FORMULA': FORMULA, 'MOLARMASS':MW, 'LIQDENS':normalliqdens, 'TC':TC, 'PC':PC, 'ACSFACT':acsfact, 'NORMBOIL':NORMBOIL, 'MWAVG':MW, 'Vc':Vc, 'PVMODEL':PVMODEL, 'Href':Href, 'CPA':CPA, 'CPB':CPB, 'CPC':CPC, 'CPD':CPD,'CPE':CPE, 'AntoineVapPresLiqType':AntoineVapPresLiqType, 'ANTOINEA':ANTOINEA, 'ANTOINEB':ANTOINEB, 'ANTOINEC':ANTOINEC, 'ANTOINED':ANTOINED, 'ANTOINEE':ANTOINEE, 'DIPOLEMOMENT':DIPOLEMOMENT, 'VISCFACT':VISCFACT, 'RACKETZ':RACKETZ, 'volcorrSRK_T':volcorrSRK_T, 'LJDIAMETER':LJDIAMETER, 'LJEPS':LJEPS, 'SphericalCoreRadius':SphericalCoreRadius, 'HEATOFFUSION':HEATOFFUSION,'TRIPLEPOINTPRESSURE':TRIPLEPOINTPRESSURE, 'TRIPLEPOINTTEMPERATURE':TRIPLEPOINTTEMPERATURE, 'TRIPLEPOINTDENSITY':TRIPLEPOINTDENSITY, 'MELTINGPOINTTEMPERATURE':MELTINGPOINTTEMPERATURE, 'ENTHALPYOFFORMATION':ENTHALPYOFFORMATION}
component

{'ID': 1188,
 'NAME': 'Arsenic ',
 'CASnumber': '7440-38-2',
 'COMPTYPE': 'Arsenic ',
 'COMPINDEX': 195,
 'FORMULA': 'As',
 'MOLARMASS': 74.9216,
 'LIQDENS': 5343.72282881906,
 'TC': 1399.85,
 'PC': 223.0,
 'ACSFACT': -0.368,
 'NORMBOIL': 615.0,
 'MWAVG': 74.9216,
 'Vc': 35.0,
 'PVMODEL': 'Classic',
 'Href': 302500.0,
 'CPA': 37.978352,
 'CPB': -0.07461815,
 'CPC': 0.0003018813,
 'CPD': 0,
 'CPE': 0,
 'AntoineVapPresLiqType': 'pow10KPa',
 'ANTOINEA': 0,
 'ANTOINEB': 0,
 'ANTOINEC': 0,
 'ANTOINED': 0.0,
 'ANTOINEE': 0.0,
 'DIPOLEMOMENT': None,
 'VISCFACT': 0.215,
 'RACKETZ': 0.0,
 'volcorrSRK_T': 0.0,
 'LJDIAMETER': None,
 'LJEPS': None,
 'SphericalCoreRadius': 1.0,
 'HEATOFFUSION': 24440.0,
 'TRIPLEPOINTPRESSURE': 0,
 'TRIPLEPOINTTEMPERATURE': 0,
 'TRIPLEPOINTDENSITY': 0,
 'MELTINGPOINTTEMPERATURE': 1090.15,
 'ENTHALPYOFFORMATION': 302500.0}

# Test new component

In [165]:
newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))
newcomp_df.to_csv('COMPupdated.csv')
newcomp_df


#jNeqSim.util.database.NeqSimDataBase.updateTable('COMP', '/content/COMPupdated.csv')


#and then use the new component and table

from neqsim.thermo import fluid


from neqsim import jNeqSim
from neqsim.thermo import fluid, TPflash

fluid1 = fluid('srk')
fluid1.addComponent(componentName, 1.0)
#TPflash(fluid1)

newcomp_df

<ipython-input-165-dd8a663a760b>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))

,ID,NAME,CASnumber,COMPTYPE,COMPINDEX,FORMULA,MOLARMASS,LIQDENS,TC,PC,...,CPliquid1,CPliquid2,CPliquid3,CPliquid4,CPliquid5,MCPR1,MCPR2,MCPR3,PARACHOR_CPA,Vc
0,1,methane,74-82-8,HC,1,CH4,16.0430,0.422182,-82.590000,45.99,...,0.0,0.00,0.00000,0.0,0.0,0.392340,0.00000,0.00000,77.300000,NaN
1,2,ethane,74-84-0,HC,2,C2H6,30.0700,0.544459,32.170000,48.72,...,0.0,0.00,0.00000,0.0,0.0,0.520050,0.00430,0.10292,108.900000,NaN
2,3,Cl-,0-0-0-0,ion,3,Cl-,35.4500,0.797000,444.150000,290.89,...,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000,NaN
3,4,Na+,0-0-0-0,ion,4,Na+,22.9900,0.797000,444.150000,290.89,...,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000,NaN
4,5,Mg++,0-0-0-0,ion,5,Mg++,24.3100,0.797000,444.150000,290.89,...,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,1184,cis-14-DM-cy-C6,624-29-3,HC,147,C,112.2200,0.422182,325.000000,29.64,...,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000,NaN
191,1185,trans-14-DM-cy-C6,2207-04-7,HC,147,C,112.2200,0.422182,316.667017,29.64,...,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000,NaN
192,1186,PG,57-55-6,glycol,1186,propyleneglycol,76.0950,1.036000,352.850000,61.00,...,35540.0,436.78,-0.18486,0.0,0.0,0.910030,1.34996,-1.89002,151.817428,NaN
193,1187,ammonia,7664-41-7,other,1187,Nh3,17.0310,0.730000,132.250000,113.00,...,105800.0,-362.23,0.93790,0.0,0.0,1.224003,-0.27350,-0.39823,87.543853,NaN
0,1188,diethylene glycol,111-46-6,diethylene glycol,195,C4H10O3,106.1204,900.650948,476.850000,47.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325.0

In [155]:
newcomp_df.iloc[-1]

ID                           1188
NAME            diethylene glycol
CASnumber                111-46-6
COMPTYPE        diethylene glycol
COMPINDEX                    1188
                      ...
MCPR1                         NaN
MCPR2                         NaN
MCPR3                         NaN
PARACHOR_CPA                  NaN
Vc                          325.0
Name: 0, Length: 151, dtype: object

In [89]:
comp_df.ID.max()

1187