<a href="https://colab.research.google.com/github/EvenSol/NeqSim-Colab/blob/master/notebooks/PVT/parameter_database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
%%capture
!pip install neqsim
!pip install wget

In [14]:
%%capture
!wget https://raw.githubusercontent.com/equinor/neqsim/master/src/main/resources/data/COMP.csv
!wget https://raw.githubusercontent.com/equinor/neqsim/master/src/main/resources/data/INTER.csv

In [15]:
import pandas as pd
comp_df = pd.read_csv('COMP.csv')
comp_df

,ID,NAME,CASnumber,COMPTYPE,COMPINDEX,FORMULA,MOLARMASS,LIQDENS,TC,PC,...,CPsolid5,CPliquid1,CPliquid2,CPliquid3,CPliquid4,CPliquid5,MCPR1,MCPR2,MCPR3,PARACHOR_CPA
0,1,methane,74-82-8,HC,1,CH4,16.043,0.422182,-82.590000,45.99,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.392340,0.00000,0.00000,77.300000
1,2,ethane,74-84-0,HC,2,C2H6,30.070,0.544459,32.170000,48.72,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.520050,0.00430,0.10292,108.900000
2,3,Cl-,0-0-0-0,ion,3,Cl-,35.450,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
3,4,Na+,0-0-0-0,ion,4,Na+,22.990,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
4,5,Mg++,0-0-0-0,ion,5,Mg++,24.310,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,1183,trans-12-DM-cy-C6,6876-23-9,HC,147,C,112.220,0.422182,322.777002,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
190,1184,cis-14-DM-cy-C6,624-29-3,HC,147,C,112.220,0.422182,325.000000,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
191,1185,trans-14-DM-cy-C6,2207-04-7,HC,147,C,112.220,0.422182,316.667017,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
192,1186,PG,57-55-6,glycol,1186,propyleneglycol,76.095,1.036000,352.850000,61.00,...,0.0,35540.0,436.78,-0.18486,0.0,0.0,0.910030,1.34996,-1.89002,151.817428
193,1187,ammonia,7664-41-7,other,1187,Nh3,17.031,0.730000,132.250000,113.00,...,0.0,105800.0,-362.23,0.93790,0.0,0.0,1.224003,-0.27350,-0.39823,87.543853

# Components

In [16]:
comp_df['NAME']

0                methane
1                 ethane
2                    Cl-
3                    Na+
4                   Mg++
             ...
189    trans-12-DM-cy-C6
190      cis-14-DM-cy-C6
191    trans-14-DM-cy-C6
192                   PG
193              ammonia
Name: NAME, Length: 194, dtype: object

# How to add a new component

In [17]:
component = { 'ID': len(comp_df), 'NAME': 'methane2', 'CASnumber': '74-82-8', 'COMPTYPE': 'HC', 'COMPINDEX': 1000, 'FORMULA':'CH4', 'MOLARMASS':16.04}
newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))
newcomp_df.to_csv('COMPupdated.csv')
newcomp_df

<ipython-input-17-306cf15eb095>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))

,ID,NAME,CASnumber,COMPTYPE,COMPINDEX,FORMULA,MOLARMASS,LIQDENS,TC,PC,...,CPsolid5,CPliquid1,CPliquid2,CPliquid3,CPliquid4,CPliquid5,MCPR1,MCPR2,MCPR3,PARACHOR_CPA
0,1,methane,74-82-8,HC,1,CH4,16.043,0.422182,-82.590000,45.99,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.392340,0.00000,0.00000,77.300000
1,2,ethane,74-84-0,HC,2,C2H6,30.070,0.544459,32.170000,48.72,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.520050,0.00430,0.10292,108.900000
2,3,Cl-,0-0-0-0,ion,3,Cl-,35.450,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
3,4,Na+,0-0-0-0,ion,4,Na+,22.990,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
4,5,Mg++,0-0-0-0,ion,5,Mg++,24.310,0.797000,444.150000,290.89,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,1184,cis-14-DM-cy-C6,624-29-3,HC,147,C,112.220,0.422182,325.000000,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
191,1185,trans-14-DM-cy-C6,2207-04-7,HC,147,C,112.220,0.422182,316.667017,29.64,...,0.0,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000
192,1186,PG,57-55-6,glycol,1186,propyleneglycol,76.095,1.036000,352.850000,61.00,...,0.0,35540.0,436.78,-0.18486,0.0,0.0,0.910030,1.34996,-1.89002,151.817428
193,1187,ammonia,7664-41-7,other,1187,Nh3,17.031,0.730000,132.250000,113.00,...,0.0,105800.0,-362.23,0.93790,0.0,0.0,1.224003,-0.27350,-0.39823,87.543853
0,194,methane2,74-82-8,HC,1000,CH4,16.040,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# How to use new table in database 
How to set path to database (if not to use default database)

In [18]:
from neqsim import jNeqSim

#jNeqSim.util.database.NeqSimDataBase.updateTable('COMP', '/content/COMPupdated.csv')


#and then use the new component and table

from neqsim.thermo import fluid

#fluid1 = fluid('srk')
#fluid1.addCOmponent('methane2', 1.0)
#TPflash(fluid1)

# Interaction parameter database

In [19]:
import pandas as pd
inter_df = pd.read_csv('INTER.csv')
inter_df

,ID,COMP1,COMP2,HVTYPE,KIJSRK,KIJTSRK,KIJTType,KIJPR,KIJTPR,KIJPCSAFT,...,cpakijT_SRK,cpakijx_SRK,cpakjix_SRK,cpakij_PR,KIJWSunifac,aijDesMath,bijDesMath,cpaAssosiationType,cpaBetaCross,cpaEpsCross
0,6933.0,water,methane,HV,0.4500,0.0,0.0,0.6510,-1.385,0.0,...,0.002606,-0.827413,-0.827413,0.1612,0.0,0.0,0.0,0.0,0.0,0.0
1,6935.0,ethanol,methane,HV,0.1300,0.0,0.0,0.1300,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
2,6936.0,MEG,methane,Classic,0.2000,0.0,0.0,0.2000,0.000,0.0,...,0.000000,0.131438,0.070213,0.1340,0.0,0.0,0.0,0.0,0.0,0.0
3,6937.0,DEG,methane,Classic,0.2000,0.0,0.0,0.2000,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
4,6938.0,TEG,methane,Classic,0.2000,0.0,0.0,0.2000,0.000,0.0,...,0.000000,0.162000,0.130000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1360,8819.0,n-octane,nitrogen,Classic,0.0800,0.0,0.0,0.0800,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
1361,8820.0,n-nonane,nitrogen,Classic,0.0800,0.0,0.0,0.0800,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
1362,8821.0,nC10,nitrogen,Classic,0.0800,0.0,0.0,0.0800,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
1363,8822.0,n-butane,water,HV,0.5000,0.0,0.0,0.5000,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
1364,8823.0,ammonia,water,Classic,-0.0789,0.0,0.0,-0.0789,0.000,0.0,...,0.000000,-0.153000,-0.153000,-0.1530,0.0,0.0,0.0,0.0,0.0,0.0

Adding a new interaction between methane2 and propane

In [20]:
interNew = { 'ID': len(inter_df), 'COMP1': 'methane2', 'COMP2': 'propane', 'KIJSRK': 0.003}
newinter_df = inter_df.append(pd.DataFrame(interNew, index=[0])).fillna(0)
newinter_df.to_csv('INTERupdated.csv')
newinter_df

<ipython-input-20-1d604ce1aac9>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  newinter_df = inter_df.append(pd.DataFrame(interNew, index=[0])).fillna(0)

,ID,COMP1,COMP2,HVTYPE,KIJSRK,KIJTSRK,KIJTType,KIJPR,KIJTPR,KIJPCSAFT,...,cpakijT_SRK,cpakijx_SRK,cpakjix_SRK,cpakij_PR,KIJWSunifac,aijDesMath,bijDesMath,cpaAssosiationType,cpaBetaCross,cpaEpsCross
0,6933.0,water,methane,HV,0.4500,0.0,0.0,0.6510,-1.385,0.0,...,0.002606,-0.827413,-0.827413,0.1612,0.0,0.0,0.0,0.0,0.0,0.0
1,6935.0,ethanol,methane,HV,0.1300,0.0,0.0,0.1300,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
2,6936.0,MEG,methane,Classic,0.2000,0.0,0.0,0.2000,0.000,0.0,...,0.000000,0.131438,0.070213,0.1340,0.0,0.0,0.0,0.0,0.0,0.0
3,6937.0,DEG,methane,Classic,0.2000,0.0,0.0,0.2000,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
4,6938.0,TEG,methane,Classic,0.2000,0.0,0.0,0.2000,0.000,0.0,...,0.000000,0.162000,0.130000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1361,8820.0,n-nonane,nitrogen,Classic,0.0800,0.0,0.0,0.0800,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
1362,8821.0,nC10,nitrogen,Classic,0.0800,0.0,0.0,0.0800,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
1363,8822.0,n-butane,water,HV,0.5000,0.0,0.0,0.5000,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0
1364,8823.0,ammonia,water,Classic,-0.0789,0.0,0.0,-0.0789,0.000,0.0,...,0.000000,-0.153000,-0.153000,-0.1530,0.0,0.0,0.0,0.0,0.0,0.0
0,1365.0,methane2,propane,0,0.0030,0.0,0.0,0.0000,0.000,0.0,...,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0

And then use the new interaction

In [25]:
#jNeqSim.util.database.NeqSimDataBase.updateTable('INTER', '/content/INTERupdated.csv')


#and then use the new component and table

from neqsim.thermo import fluid,TPflash

fluid1 = fluid('srk')
fluid1.addComponent('methane2', 1.0)
fluid1.addComponent('propane', 1.0)
TPflash(fluid1)
#print(fluid1.getPhase(0).getMIxingRUle().getkij(0,1))

# Update parameters in the database

In [27]:
comp_df.at[0,'TC']=-82.2590000 #updating critical temperature of methane
comp_df.to_csv('COMPupdatedparam.csv')
#jNeqSim.util.database.NeqSimDataBase.updateTable('COMP', '/content/COMPupdatedparam.csv')

# Add new components using the Chemicals package
https://github.com/CalebBell/chemicals

https://chemicals.readthedocs.io/

In [28]:
pip install chemicals

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: chemicals in /usr/local/lib/python3.9/dist-packages (1.1.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.9/dist-packages (from chemicals) (1.10.1)
Requirement already satisfied: fluids>=1.0.21 in /usr/local/lib/python3.9/dist-packages (from chemicals) (1.0.22)
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (from chemicals) (1.4.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from chemicals) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas->chemicals) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas->chemicals) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas->chemicals) (1.16.0)

In [67]:
from chemicals.identifiers import CAS_from_any, search_chemical, pubchem_db
componentName = 'methane' #enter compoent name/CAS number/etx
comp = search_chemical(componentName)
print(comp)
CAS_number = CAS_from_any(componentName)
FORMULA = comp.formula

<ChemicalMetadata, name=methane, formula=CH4, smiles=C, MW=16.043>

In [72]:
ID = comp_df.ID.max()+1
COMPINDEX = len(comp_df. index)+1
R = 8.3144598 # J/Kmol

from chemicals import CAS_from_any, MW, Tb, Tm, Tc, Pc, Vc, Hfus, Hfs, Hfl, Hfg, S0s, S0l, S0g, rho_to_API 
from chemicals.identifiers import ChemicalMetadata,pubchem_db 
from chemicals.iapws import iapws95_rhol_sat
from chemicals.acentric import omega
from chemicals.phase_change import Tb
from chemicals.reaction import Hfg

from chemicals.vapor_pressure import Psat_data_AntoinePoling
from chemicals.dipole import dipole_moment
from chemicals.volume import rho_data_COSTALD

MW = MW(CAS_number) # gr/mol

#https://chemicals.readthedocs.io/chemicals.critical.html#chemicals.critical.Tc_methods
TC = Tc(CAS_number)-273.15 #C
PC = Pc(CAS_number)/1e5 #bara
Vc = Vc(CAS_number)*1e6

#https://chemicals.readthedocs.io/chemicals.acentric.html
acsfact = omega(CAS_number)

#https://chemicals.readthedocs.io/chemicals.phase_change.html#boiling-point
NORMBOIL = Tb(CAS_number)-273.15 #C
PVMODEL = 'Classic'
Href = Hfg(CAS_number)

#https://chemicals.readthedocs.io/chemicals.volume.html#pure-low-pressure-liquid-correlations
from chemicals.volume import COSTALD,Vm_to_rho
normalliqdens = Vm_to_rho(COSTALD(NORMBOIL+273.15, TC+273.15,Vc/1e6,acsfact),MW)

# https://github.com/equinor/neqsim/blob/67bfec956176ffcad490a288fbcd7e17844f3a1c/src/main/java/neqsim/thermo/component/Component.java#L1277
# getCpA() + getCpB() * temperature + getCpC() * Math.pow(temperature, 2)+ getCpD() * Math.pow(temperature, 3) + getCpE() * Math.pow(temperature, 4); temperature in K
# https://chemicals.readthedocs.io/chemicals.heat_capacity.html#chemicals.heat_capacity.ShomateRange.calculate_integral
from chemicals.heat_capacity import Cp_data_Poling
try:
  cpdata = Cp_data_Poling.loc[CAS_number]
  CPA=cpdata['a0']*R
  CPB=cpdata['a1']*R
  CPC=cpdata['a2']*R
  CPD=cpdata['a3']*R
  CPE = cpdata['a4']*R 
except:
  CPA=37.978352
  CPB=-0.07461815
  CPC=0.0003018813
  CPD=0
  CPE = 0


#https://github.com/equinor/neqsim/blob/67bfec956176ffcad490a288fbcd7e17844f3a1c/src/main/java/neqsim/thermo/component/Component.java#L1194
#pow10 : Math.pow(10.0, AntoineA - (AntoineB / (temp + AntoineC - 273.15)));
#https://chemicals.readthedocs.io/chemicals.vapor_pressure.html#id62
try:
  AntoineVapPresLiqType = 'pow10KPa'
  antoinepol = Psat_data_AntoinePoling.loc[CAS_number]
  ANTOINEA = antoinepol['A']
  ANTOINEB = antoinepol['B']
  ANTOINEC = antoinepol['C']
  ANTOINED= 0.0
  ANTOINEE= 0.0
except:
  AntoineVapPresLiqType = 'pow10KPa'
  ANTOINEA =0
  ANTOINEB = 0
  ANTOINEC = 0
  ANTOINED= 0.0
  ANTOINEE= 0.0 
#https://chemicals.readthedocs.io/chemicals.dipole.html
#https://github.com/equinor/neqsim/blob/67bfec956176ffcad490a288fbcd7e17844f3a1c/src/main/java/neqsim/thermo/component/Component.java#L741
DIPOLEMOMENT = dipole_moment(CAS_number)

VISCFACT = 0.215

#https://chemicals.readthedocs.io/chemicals.volume.html?highlight=racket#chemicals.volume.Rackett
try:
  RACKETZ = rho_data_COSTALD.loc[CAS_number]['Z_RA']
  volcorrSRK_T = 0.0
except:
  RACKETZ = 0.0
  volcorrSRK_T = 0.0

#https://chemicals.readthedocs.io/chemicals.lennard_jones.html?highlight=molecular_diameter
from chemicals.lennard_jones import molecular_diameter
from chemicals.lennard_jones import Stockmayer
from chemicals.molecular_geometry import RG
try:
  LJDIAMETER = molecular_diameter(CAS_number)
  LJEPS = Stockmayer(CAS_number)
except:
  LJDIAMETER = 1.0
  LJEPS = 1.0

try:
  SphericalCoreRadius = RG(CAS_number)*1e10/2.0
except:
  SphericalCoreRadius = 1.0

#https://chemicals.readthedocs.io/chemicals.phase_change.html?highlight=Hfus#heat-of-fusion
HEATOFFUSION = Hfus(CAS_number)

#
from chemicals.triple import Tt, Pt
try:
  TRIPLEPOINTTEMPERATURE = Tt(CAS_number)
  TRIPLEPOINTPRESSURE = Pt(CAS_number)/1e5
  TRIPLEPOINTDENSITY = normalliqdens
except:
  TRIPLEPOINTTEMPERATURE = 0
  TRIPLEPOINTPRESSURE = 0
  TRIPLEPOINTDENSITY = 0

#https://chemicals.readthedocs.io/chemicals.phase_change.html?highlight=MELTING#module-chemicals.phase_change
from chemicals.phase_change import Tm
MELTINGPOINTTEMPERATURE= Tm(CAS_number)

from chemicals.reaction import Hfg
ENTHALPYOFFORMATION = Hfg(CAS_number)

#https://chemicals.readthedocs.io/chemicals.viscosity.html?highlight=critical%20Viscosity#chemicals.viscosity.viscosity_gas_Gharagheizi
from chemicals.viscosity import Yoon_Thodos
criticalViscosity = Yoon_Thodos((TC+273.15),(TC+273.15), (PC*1e5), MW )

#https://chemicals.readthedocs.io/chemicals.phase_change.html?highlight=heat%20of%20vapour#heat-of-vaporization-at-tb-correlations
from chemicals.phase_change import Riedel
try:
  HEATOFVAPORIZATIONCOEFS1 =Riedel(NORMBOIL+273.15, (TC+273.15), PC*1e5)
  HEATOFVAPORIZATIONCOEFS2 = 0.0
  HEATOFVAPORIZATIONCOEFS3 = 0.0
  HEATOFVAPORIZATIONCOEFS4 = 0.0
  HEATOFVAPORIZATIONCOEFS5 = 0.0
except:
  HEATOFVAPORIZATIONCOEFS1 = 8170
  HEATOFVAPORIZATIONCOEFS2 = 0.0
  HEATOFVAPORIZATIONCOEFS3 = 0.0
  HEATOFVAPORIZATIONCOEFS4 = 0.0
  HEATOFVAPORIZATIONCOEFS5 = 0.0

from chemicals.volume import Rackett
try:
  LIQUIDDENSITYCOEFS1 = 2.92 #Vm_to_rho(Rackett(NORMBOIL+273.15, (TC+273.15), Vc/1e6, acsfact), MW)
  LIQUIDDENSITYCOEFS2 = 0.0
  LIQUIDDENSITYCOEFS3 = 0.0
  LIQUIDDENSITYCOEFS4 = 0.0
  LIQUIDDENSITYCOEFS5 = 0.0
except:
  LIQUIDDENSITYCOEFS1 = 0.0
  LIQUIDDENSITYCOEFS2 = 0.0
  LIQUIDDENSITYCOEFS3 = 0.0
  LIQUIDDENSITYCOEFS4 = 0.0
  LIQUIDDENSITYCOEFS5 = 0.0

from chemicals.volume import Rackett
try:
  SOLIDDENSITYCOEFS1 = 2.92 #Vm_to_rho(Rackett(NORMBOIL+273.15, (TC+273.15), Vc/1e6, acsfact), MW)
  SOLIDDENSITYCOEFS2 = 0.0
  SOLIDDENSITYCOEFS3 = 0.0
  SOLIDDENSITYCOEFS4 = 0.0
  SOLIDDENSITYCOEFS5 = 0.0
except:
  SOLIDDENSITYCOEFS1 = 33.022
  SOLIDDENSITYCOEFS2 = 0.0
  SOLIDDENSITYCOEFS3 = 0.0
  SOLIDDENSITYCOEFS4 = 0.0
  SOLIDDENSITYCOEFS5 = 0.0

#https://chemicals.readthedocs.io/chemicals.reaction.html?highlight=entropy#gas-absolute-entropy
from chemicals.reaction import S0g
ABSOLUTEENTROPY = S0g(CAS_number)

#https://chemicals.readthedocs.io/chemicals.phase_change.html?highlight=sublimation%20heat#heat-of-sublimation
Hsub = HEATOFFUSION + 100 # + 


component = {'ID': ID, 'NAME': componentName, 'CASnumber': CAS_number, 'COMPTYPE': componentName, 'COMPINDEX': COMPINDEX, 'FORMULA': FORMULA, 'MOLARMASS':MW, 'LIQDENS':normalliqdens, 'TC':TC, 'PC':PC, 'ACSFACT':acsfact, 'NORMBOIL':NORMBOIL, 'MWAVG':MW, 'Vc':Vc, 'PVMODEL':PVMODEL, 'Href':Href, 'CPA':CPA, 'CPB':CPB, 'CPC':CPC, 'CPD':CPD,'CPE':CPE, 'AntoineVapPresLiqType':AntoineVapPresLiqType, 'ANTOINEA':ANTOINEA, 'ANTOINEB':ANTOINEB, 'ANTOINEC':ANTOINEC, 'ANTOINED':ANTOINED, 'ANTOINEE':ANTOINEE, 'DIPOLEMOMENT':DIPOLEMOMENT, 'VISCFACT':VISCFACT, 'RACKETZ':RACKETZ, 'volcorrSRK_T':volcorrSRK_T, 'LJDIAMETER':LJDIAMETER, 'LJEPS':LJEPS, 'SphericalCoreRadius':SphericalCoreRadius, 'HEATOFFUSION':HEATOFFUSION,'TRIPLEPOINTPRESSURE':TRIPLEPOINTPRESSURE, 'TRIPLEPOINTTEMPERATURE':TRIPLEPOINTTEMPERATURE, 'TRIPLEPOINTDENSITY':TRIPLEPOINTDENSITY, 'MELTINGPOINTTEMPERATURE':MELTINGPOINTTEMPERATURE, 'ENTHALPYOFFORMATION':ENTHALPYOFFORMATION, 'criticalViscosity':criticalViscosity, 'Hsub':Hsub, 'HEATOFVAPORIZATIONCOEFS1':HEATOFVAPORIZATIONCOEFS1, 'HEATOFVAPORIZATIONCOEFS2':HEATOFVAPORIZATIONCOEFS2, 'HEATOFVAPORIZATIONCOEFS3':HEATOFVAPORIZATIONCOEFS3,'HEATOFVAPORIZATIONCOEFS4':HEATOFVAPORIZATIONCOEFS4,'HEATOFVAPORIZATIONCOEFS5':HEATOFVAPORIZATIONCOEFS5, 'LIQUIDDENSITYCOEFS1':LIQUIDDENSITYCOEFS1,'LIQUIDDENSITYCOEFS2':LIQUIDDENSITYCOEFS2,'LIQUIDDENSITYCOEFS3':LIQUIDDENSITYCOEFS3, 'LIQUIDDENSITYCOEFS4':LIQUIDDENSITYCOEFS4,'LIQUIDDENSITYCOEFS5':LIQUIDDENSITYCOEFS5, 'SOLIDDENSITYCOEFS1':SOLIDDENSITYCOEFS1, 'SOLIDDENSITYCOEFS2':SOLIDDENSITYCOEFS2,'SOLIDDENSITYCOEFS3':SOLIDDENSITYCOEFS3, 'SOLIDDENSITYCOEFS4':SOLIDDENSITYCOEFS4, 'SOLIDDENSITYCOEFS5':SOLIDDENSITYCOEFS5, 'ABSOLUTEENTROPY':ABSOLUTEENTROPY}
component

{'ID': 1188,
 'NAME': 'methane',
 'CASnumber': '74-82-8',
 'COMPTYPE': 'methane',
 'COMPINDEX': 195,
 'FORMULA': 'CH4',
 'MOLARMASS': 16.043,
 'LIQDENS': 426.7323781381438,
 'TC': -82.58599999999998,
 'PC': 45.99,
 'ACSFACT': 0.008,
 'NORMBOIL': -161.49999999999997,
 'MWAVG': 16.043,
 'Vc': 98.6,
 'PVMODEL': 'Classic',
 'Href': -74534.0,
 'CPA': 37.980452366399994,
 'CPB': -0.074622276705,
 'CPC': 0.00030189803533800004,
 'CPD': -2.83273645386e-07,
 'CPE': 9.071075641799999e-11,
 'AntoineVapPresLiqType': 'pow10KPa',
 'ANTOINEA': 8.7687,
 'ANTOINEB': 395.744,
 'ANTOINEC': -6.469,
 'ANTOINED': 0.0,
 'ANTOINEE': 0.0,
 'DIPOLEMOMENT': 0.0,
 'VISCFACT': 0.215,
 'RACKETZ': 0.2892,
 'volcorrSRK_T': 0.0,
 'LJDIAMETER': 3.58484,
 'LJEPS': 167.15,
 'SphericalCoreRadius': 0.570347,
 'HEATOFFUSION': 940.0,
 'TRIPLEPOINTPRESSURE': 0.11691038486842101,
 'TRIPLEPOINTTEMPERATURE': 90.698,
 'TRIPLEPOINTDENSITY': 426.7323781381438,
 'MELTINGPOINTTEMPERATURE': 90.75,
 'ENTHALPYOFFORMATION': -74534.0,
 'criticalViscosity': 7.311571824058866e-06,
 'Hsub': 1040.0,
 'HEATOFVAPORIZATIONCOEFS1': 8301.615602012555,
 'HEATOFVAPORIZATIONCOEFS2': 0.0,
 'HEATOFVAPORIZATIONCOEFS3': 0.0,
 'HEATOFVAPORIZATIONCOEFS4': 0.0,
 'HEATOFVAPORIZATIONCOEFS5': 0.0,
 'LIQUIDDENSITYCOEFS1': 2.92,
 'LIQUIDDENSITYCOEFS2': 0.0,
 'LIQUIDDENSITYCOEFS3': 0.0,
 'LIQUIDDENSITYCOEFS4': 0.0,
 'LIQUIDDENSITYCOEFS5': 0.0,
 'SOLIDDENSITYCOEFS1': 2.92,
 'SOLIDDENSITYCOEFS2': 0.0,
 'SOLIDDENSITYCOEFS3': 0.0,
 'SOLIDDENSITYCOEFS4': 0.0,
 'SOLIDDENSITYCOEFS5': 0.0,
 'ABSOLUTEENTROPY': 186.3}

# Test new component

In [63]:
newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))
newcomp_df.to_csv('COMPupdated.csv')
newcomp_df


#jNeqSim.util.database.NeqSimDataBase.updateTable('COMP', '/content/COMPupdated.csv')


#and then use the new component and table

from neqsim.thermo import fluid


from neqsim import jNeqSim
from neqsim.thermo import fluid, TPflash

fluid1 = fluid('srk')
fluid1.addComponent(componentName, 1.0)
#TPflash(fluid1)

newcomp_df

<ipython-input-63-dd8a663a760b>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  newcomp_df = comp_df.append(pd.DataFrame(component, index=[0]))

,ID,NAME,CASnumber,COMPTYPE,COMPINDEX,FORMULA,MOLARMASS,LIQDENS,TC,PC,...,CPliquid1,CPliquid2,CPliquid3,CPliquid4,CPliquid5,MCPR1,MCPR2,MCPR3,PARACHOR_CPA,Vc
0,1,methane,74-82-8,HC,1,CH4,16.0430,0.422182,-82.259000,45.990000,...,0.0,0.00,0.00000,0.0,0.0,0.392340,0.00000,0.00000,77.300000,NaN
1,2,ethane,74-84-0,HC,2,C2H6,30.0700,0.544459,32.170000,48.720000,...,0.0,0.00,0.00000,0.0,0.0,0.520050,0.00430,0.10292,108.900000,NaN
2,3,Cl-,0-0-0-0,ion,3,Cl-,35.4500,0.797000,444.150000,290.890000,...,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000,NaN
3,4,Na+,0-0-0-0,ion,4,Na+,22.9900,0.797000,444.150000,290.890000,...,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000,NaN
4,5,Mg++,0-0-0-0,ion,5,Mg++,24.3100,0.797000,444.150000,290.890000,...,0.0,0.00,0.00000,0.0,0.0,0.000000,0.00000,0.00000,207.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,1184,cis-14-DM-cy-C6,624-29-3,HC,147,C,112.2200,0.422182,325.000000,29.640000,...,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000,NaN
191,1185,trans-14-DM-cy-C6,2207-04-7,HC,147,C,112.2200,0.422182,316.667017,29.640000,...,0.0,0.00,0.00000,0.0,0.0,0.628820,0.70114,-0.78437,0.000000,NaN
192,1186,PG,57-55-6,glycol,1186,propyleneglycol,76.0950,1.036000,352.850000,61.000000,...,35540.0,436.78,-0.18486,0.0,0.0,0.910030,1.34996,-1.89002,151.817428,NaN
193,1187,ammonia,7664-41-7,other,1187,Nh3,17.0310,0.730000,132.250000,113.000000,...,105800.0,-362.23,0.93790,0.0,0.0,1.224003,-0.27350,-0.39823,87.543853,NaN
0,1188,nitrogen,7727-37-9,nitrogen,195,N2,28.0134,811.626083,-146.950000,33.943875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.5

In [ ]:
newcomp_df.iloc[-1]

In [ ]:
comp_df.ID.max()